---
- name: set_vars | Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __access_conf_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    __access_conf_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __access_conf_vars_file is file
  tags: always
