---
name: Automated Ansible Role Documentation

on:
  # Leaving this here for potential, likely will block pushes to main.
  # push:
  #   branches: ["main"]
  #   paths:
  #     - 'roles/**/meta/argument_specs.yml'
  #     - 'roles/**/meta/main.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'roles/**/meta/argument_specs.yml'
      - 'roles/**/meta/main.yml'

jobs:
  aar_docs:
    name: create roles readme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roles:
          - access_conf
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install aar_doc
        run: pip3 install aar_doc

      - name: Run aar_doc
        run: aar_doc roles/${{ matrix.roles }} markdown

      - name: Output diff
        run: git diff roles/${{ matrix.roles }}/README.md

      - name: Push README
        if: github.event_name != 'pull_request'
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update ${{ matrix.roles }} README'
          files: roles/${{ matrix.roles }}/README.md
          rebase: true
          name: Server Baseline Workflows
          email: nb623107@gmail.com
