---
name: Ansible Lint

on:
  # Leaving this here for potential, likely will block pushes to main.
  push:
    branches: [main]
    paths:
      - '.ansible-lint'
      - '.github/workflows/ansible-lint.yml'
      - 'galaxy-deploy.yml'
      - 'galaxy.yml'
      - 'roles/**'
      # - 'molecule/**'
      # - 'requirements.txt'
  pull_request:
    branches: [main]
    paths:
      - '.ansible-lint'
      - '.github/workflows/ansible-lint.yml'
      - 'galaxy-deploy.yml'
      - 'galaxy.yml'
      - 'roles/**'
      # - 'molecule/**'
      # - 'requirements.txt'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # This runs twice, once to install the collections and roles, because
      # the current action is unable to resolve FQCN for modules on first pass
      - name: Install required collections and roles
        uses: ansible/ansible-lint@v25
        with:
          args: "galaxy.yml -v"
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25
        with:
          args: "-v"
