---
name: Ansible Lint

on:
  # Leaving this here for potential, likely will block pushes to main.
  # push:
  #   branches: ["main"]
  #   paths:
  #     - 'roles/**'
  #     # - 'molecule/**'
  #     # - 'requirements.txt'
  #     - '.github/workflows/ansible-lint.yml'
  #     - '.ansible-lint'
  pull_request:
    branches: ["main"]
    paths:
      - 'roles/**'
      # - 'molecule/**'
      # - 'requirements.txt'
      - '.github/workflows/ansible-lint.yml'
      - '.ansible-lint'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
