---
name: Ansible Lint

on:
  # Leaving this here for potential, likely will block pushes to main.
  push:
    branches: [main]
    paths:
      - '.ansible-lint'
      - '.github/workflows/ansible-lint.yml'
      - 'galaxy-deploy.yml'
      - 'galaxy.yml'
      - 'roles/**'
      # - 'molecule/**'
      # - 'requirements.txt'
  pull_request:
    branches: [main]
    paths:
      - '.ansible-lint'
      - '.github/workflows/ansible-lint.yml'
      - 'galaxy-deploy.yml'
      - 'galaxy.yml'
      - 'roles/**'
      # - 'molecule/**'
      # - 'requirements.txt'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
