---
name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - assigned
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    if: github.repository == 'barstown/ansible-collection-server_baseline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
